build_image:
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASS 
    script:
        - docker build -t gavenzheng/mercury:freelancer-app .
        - docker push gavenzheng/mercury:freelancer-app